### ISSUE TITLE
前端渲染异常

### ISSUE THREAD

**Issue by 5ime** [ProbiusOfficial/CTF-QuickStart#15]
如图所示，多出一行空行导致前端渲染异常
![image](https://github.com/ProbiusOfficial/CTF-QuickStart/assets/31686695/1afbebed-6b59-48c3-a64c-f216f34c3c3f)
![image](https://github.com/ProbiusOfficial/CTF-QuickStart/assets/31686695/8d8344b9-effa-46ab-944f-f892a58b5e36)

**Comment by ProbiusOfficial** [comment]
坏了，生产环境改代码被人发现了（逃
感谢反馈 x

**Comment by ProbiusOfficial** [comment]
已经修复
