### ISSUE TITLE
入门手册多了一个字奥

### ISSUE THREAD

**Issue by Lniosy** [ProbiusOfficial/CTF-QuickStart#21]
https://github.com/ProbiusOfficial/CTF-QuickStart/blob/main/QuickStart.md
![图片](https://github.com/ProbiusOfficial/CTF-QuickStart/assets/91119236/6dfeb21b-e3b7-4b4f-9cad-6381425de8d4)
多了一个字

**Comment by ProbiusOfficial** [comment]
感谢反馈已经在同样文案的地方修复
