### ISSUE TITLE
port or prot？

### ISSUE THREAD

**Issue by Hunt3rKun** [ProbiusOfficial/CTF-QuickStart#3]
![image](https://user-images.githubusercontent.com/53427217/232288530-32b20ec3-f3b1-4b19-85bf-2e04e3ebc4b6.png)
不知道是不是我认错了

**Comment by ProbiusOfficial** [comment]
咳咳 我错了（逃 ε=ε=ε=┏(゜ロ゜;)┛

**Comment by ProbiusOfficial** [comment]
修改了 感谢  (。•̀ᴗ-)✧
