### ISSUE TITLE
AWD内容合并请求

### ISSUE THREAD

**Issue by Yeuoly** [ProbiusOfficial/CTF-QuickStart#37]
随着自己已经基本上离开CTF这个圈子了，很多手里以前产出的内容觉得也该公开了，想从一个AWD的自制PWN通防开始吧，实测在21年湖湘杯中pass全部pwn题check，涉及到信号拦截，进程控制，ELF篡改等内容，如果同意合并的话我会提PR到这个仓库

**Comment by ProbiusOfficial** [comment]
您好呀~非常感谢您愿意分享您之前的成果和经验！！
随时欢迎您提PR，提交过程中有任何问题或需要协助，请随时与我们联系ww
