### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by ruanzy506** [ProbiusOfficial/CTF-QuickStart#50]
https://ctf.probius.xyz/HC_MISC/memory/#volatility3
![image](https://github.com/ProbiusOfficial/CTF-QuickStart/assets/37685587/95037e62-d4fc-425c-9606-9cd6db2447ca)

**Comment by ProbiusOfficial** [comment]
> https://ctf.probius.xyz/HC_MISC/memory/#volatility3
> ![image](https://github.com/ProbiusOfficial/CTF-QuickStart/assets/37685587/95037e62-d4fc-425c-9606-9cd6db2447ca)
> 

已收到，将在下次更新时修正。
您也可以点击编辑该页面直接编辑后提交。
感谢您对helloCTF项目的支持。

**Comment by ProbiusOfficial** [comment]
已经修复，感谢支持。
