### ISSUE TITLE
Burp安装教程的附件

### ISSUE THREAD

**Issue by Lil-Ran** [ProbiusOfficial/CTF-QuickStart#6]
提供一个huang1111网盘分流，可免登录高速下载：

https://pan.huang1111.cn/s/1gEBIv

另外，建议发大文件的同时提供哈希值。

**Comment by ProbiusOfficial** [comment]
收到反馈 会在下次更新时改进
同时 资源的下载问题 也会同步解决 后续如果会涉及到对应的问题 也会避免
感谢建议
