### ISSUE TITLE
环境及软件配置

### ISSUE THREAD

**Issue by Abyssun** [ProbiusOfficial/CTF-QuickStart#7]
我看那里是还空着，假如有自己写的文档我可以上传吗？
另外，觉得可以开个基础工具库的文档

**Comment by ProbiusOfficial** [comment]
都可以 欢迎Pr ww

**Comment by ProbiusOfficial** [comment]
不过要注意 蚁剑和bp的文档已经在文件夹中写了 详细见Software_Installation文件夹
